export const CI_CITIES: string[] = [
  // Abidjan (ville principale avec communes)
  'Abidjan',
  
  // Villes de Côte d'Ivoire avec établissements de santé
  'Aboisso',
  'Adzopé',
  'Adiaké',
  'Agboville',
  'Agnibilékrou',
  'Anyama',
  'Arrah',
  'Béoumi',
  'Bondoukou',
  'Bongouanou',
  'Bouna',
  'Bouaflé',
  'Bouaké',
  'Boundiali',
  'Dabou',
  'Danané',
  'Daoukro',
  'Dimbokro',
  'Dikodougou',
  'Divo',
  'Facobly',
  'Ferkessédougou',
  'Fresco',
  'Grand-Bassam',
  'Grand-Lahou',
  'Guiglo',
  'Guitry',
  'Issia',
  'Jacqueville',
  'Kani',
  'Katiola',
  'Kong',
  'Kounahiri',
  'Kouto',
  'Lakota',
  'Mankono',
  'M\'Batto',
  'Méagui',
  'Minignan',
  'Odienné',
  'Oumé',
  'Sakassou',
  'Sassandra',
  'Séguéla',
  'Sinématiali',
  'Soubré',
  'Tabou',
  'Tanda',
  'Tiapoum',
  'Tiassalé',
  'Tiébissou',
  'Touba',
  'Toulepleu',
  'Toumodi',
  'Yamoussoukro',
  'Zouan-Hounien',
  'Zuénoula',
  
  // Nouvelles villes ajoutées (décembre 2024)
  'Akoupé',
  'Bloléquin',
  'Dabakala',
  'Djékanou',
  'Grand-Béréby',
  'Grabo',
  'Guibéroua',
  'Koun-Fao',
  'N\'Douci',
  'Prikro',

  // Autres villes importantes (non encore intégrées dans la base santé)
  'Korhogo',
  'Daloa',
  'Gagnoa',
  'Man',
  'Duékoué',
  'Abengourou',
  'La Mé',
  'Sinfra',
  'Vavoua',
  'Grand-Béreby',
  'Bloléquin',
  'Bonoua',
  'San-Pédro',
  'Buyo',
  'Saïoua',
];