export const CI_CITIES: string[] = [
  // Abidjan (communes/quartiers)
  'Abobo',
  'Adjamé',
  'Anyama',
  'Attécoubé',
  'Bingerville',
  'Cocody',
  'Angré',
  'Plateau Dokui',
  'Williamsville',
  'Koumassi',
  'Marcory',
  'Plateau',
  'Port-Bouët',
  'Treichville',
  'Songon',
  'Yopougon',

  // Grandes villes et principales localités
  'Bouaké',
  'Korhogo',
  'Daloa',
  'Yamoussoukro',
  'Divo',
  'Gagnoa',
  'Soubré',
  'Man',
  'Duékoué',
  'Bouaflé',
  'Guiglo',
  'Lakota',
  'Abengourou',
  'Ferké',
  'Adzopé',
  'La Mé',
  'Méagui',
  'Bondoukou',
  'Dabou',
  'Sinfra',
  'Agboville',
  'Agnéby',
  'Vavoua',
  'Danané',
  'Grand-Béreby',
  'Oumé',
  'Issia',
  'Grand-Bassam',
  'Bloléquin',
  'Bonoua',
  'Marahoué',
  'San-Pédro',
  'Zouan-Hounien',
  'Tonkpi',
  'Sassandra',
  'Séguéla',
  'Worodougou',
  'Daoukro',
  'Aboisso',
  'Buyo',
  'Saïoua',
];