export const CI_CITIES: string[] = [
  // Liste complète des villes avec établissements de santé (68 villes)
  
  // Abidjan (ville principale avec communes)
  'Abidjan',
  
  // Autres villes avec établissements de santé (ordre alphabétique)
  'Aboisso',
  'Adzopé',
  'Adiaké',
  'Agboville',
  'Agnibilékrou',
  'Akoupé',
  'Arrah',
  'Béoumi',
  'Bloléquin',
  'Bondoukou',
  'Bongouanou',
  'Bouaflé',
  'Bouaké',
  'Bouna',
  'Boundiali',
  'Dabakala',
  'Dabou',
  'Danané',
  'Daoukro',
  'Dikodougou',
  'Dimbokro',
  'Divo',
  'Djékanou',
  'Facobly',
  'Ferkessédougou',
  'Fresco',
  'Grabo',
  'Grand-Bassam',
  'Grand-Béréby',
  'Grand-Lahou',
  'Guibéroua',
  'Guiglo',
  'Guitry',
  'Issia',
  'Jacqueville',
  'Kani',
  'Katiola',
  'Kong',
  'Kounahiri',
  'Koun-Fao',
  'Kouto',
  'Lakota',
  'Mankono',
  'M\'Batto',
  'Méagui',
  'Minignan',
  'N\'Douci',
  'Odienné',
  'Oumé',
  'Prikro',
  'Sakassou',
  'Sassandra',
  'Séguéla',
  'Sinématiali',
  'Soubré',
  'Tabou',
  'Tanda',
  'Tiapoum',
  'Tiassalé',
  'Tiébissou',
  'Touba',
  'Toulepleu',
  'Toumodi',
  'Yamoussoukro',
  'Zouan-Hounien',
  'Zuénoula',

  // Autres villes importantes (non encore intégrées dans la base santé)
  'Korhogo',
  'Daloa',
  'Gagnoa',
  'Man',
  'Duékoué',
  'Abengourou',
  'La Mé',
  'Sinfra',
  'Vavoua',
  'Buyo',
  'Saïoua',
  'San-Pédro',
];